---
title: "bioecon-model"
author: "Leonardo Feitosa"
date: "02/05/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plyr)
library(janitor)
library(vroom)
library(ramlegacy)
```

```{r}
# file paths
basedir <- file.path("G:/Meu Drive/PhD Project - Fisheries bycatch/Bycatch project/Chapter 1/analyses")
ramdir <- file.path(basedir, "RAMLDB v4.495", "Excel")
outdir <- file.path(basedir, "outputs")
```

```{r}
# read in the data
ram_leg <- vroom::vroom(file.path(ramdir, "RAMLDB v4.495 (assessment data only).xlsx"))

ram_area <- load_ramlegacy(version = "4.44", tables = c("area"))

ram_stock <- load_ramlegacy(version = "4.44", tables = c("stock"))

ram_ts <- load_ramlegacy(version = "4.44", tables = c("timeseries"))

ram_ts_val <- load_ramlegacy(version = "4.44", tables = c("timeseries_values_views")) 

ram_biop_val <- load_ramlegacy(version = "4.44", tables = c("bioparams_values_views"))

ram_biop_unit <- load_ramlegacy(version = "4.44", tables = c("bioparams_units_views"))

ram_biop_source <- load_ramlegacy(version = "4.44", tables = c("bioparams_sources_views"))
```

- stock, bioparams, bioparams_values_views, bioparams_units_views, timeseries_values_views, timeseries.

```{r}
ram_area_df <- plyr::ldply(ram_area, data.frame) %>% 
  clean_names()

ram_stock_df <- plyr::ldply(ram_stock, data.frame) %>% 
  clean_names()

ram_ts_df <- plyr::ldply(ram_ts, data.frame) %>% 
  clean_names()

ram_ts_val_df <- plyr::ldply(ram_ts_val, data.frame) %>% 
  clean_names()

ram_biop_val_df <- plyr::ldply(ram_biop_val, data.frame) %>% 
  clean_names()

ram_biop_unit_df <- plyr::ldply(ram_biop_unit, data.frame) %>% 
  clean_names()

ram_biop_source_df <- plyr::ldply(ram_biop_source, data.frame) %>% 
  clean_names()
```

```{r}
ram_ts_val_tuna_like <- ram_ts_val_df %>% 
  filter(str_detect(stocklong, "tuna|shark|skate")) %>% 
  dplyr::rename(tb_best = t_bbest,
                tc_best = t_cbest,
                er_best = e_rbest,
                bdivb_msy_pref = bdiv_bmsypref,
                udivu_msy_pref = udiv_umsypref,
                bdiv_bmgt)

ram_biop_val_tuna_like <- ram_biop_val_df %>% 
  filter(str_detect(stocklong, "tuna|shark|skate")) %>% 
  dplyr::rename(tb_msy_best = t_bmsybest,
         er_msy_best = e_rmsybest,
         msy_best = ms_ybest,
         tb_mgt_best = t_bmgtbest,
         er_mgt_best = e_rmgtbest,
         tb_msy = t_bmsy,
         ssb_msy = ss_bmsy,
         f_msy = fmsy,
         er_msy = e_rmsy,
         tb_mgt = t_bmgt,
         ssb_mgt = ss_bmgt,
         f_mgt = fmgt,
         er_mgt = e_rmgt,
         tb_lim = t_blim,
         ssb_lim = ss_blim,
         er_lim = e_rlim)

write_csv(ram_ts_val_tuna_like, file = file.path(outdir, "ts_values_tuna_like.csv"), col_names = T)
write_csv(ram_biop_val_tuna_like, file = file.path(outdir, "bioparam_val_tuna_like.csv"), col_names = T)
```




