---
title: "ode_solver_test"
author: "Leonardo Feitosa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(deSolve)

basedir <- "G:/Meu Drive/PhD Project - Fisheries bycatch/Bycatch project/Chapter 1 - Simulation model/analyses/"
outdir <- file.path(basedir, "model_outs") # calls present data from raster files
```

```{r}
# define general parameters
cost <- 0.05
alpha <- 1
A_w <- 1
A_s <- 1
q_s <- 0.02
q_w <- 0.02
k_s <- 4
k_w <- 2
r_s <- 1
r_w <- 0.99
weight_s <- 1
weight_w <- 1

# define parameters that switch per scenario
beta_s1 <- 1
beta_s2 <- 0.56
beta_s3 <- 1
beta_s4 <- 0.56

beta_w1 <- 1
beta_w2 <- 1
beta_w3 <- 0.56
beta_w4 <- 0.56

f_s1 <- 0 
f_s2 <- 0.22
f_s3 <- 0
f_s4 <- 0.22

f_w1 <- 0
f_w2 <- 0
f_w3 <- 0.22
f_w4 <- 0.22

# time steps
times <- seq(0, 400, by = .1)
```


```{r}
# Define the function that calculates the derivatives
scenario_1 <- function(time, state, parameters) {
  with(as.list(c(state, parameters)), {
    
    # Calculate the derivatives
    dN_s1 <- r_s * N_s1 * (1 - (N_s1/k_s)) - (q_s * N_s1^beta_s1 * E1) 
    dN_w1 <- r_w * N_w1 * (1 - (N_w1/k_w)) - (q_w * N_w1^beta_w1 * E1) 
    dE1 <- alpha * E1 * (A_s * (q_s * N_s1^beta_s1 * E1)^-f_s1 * q_s * N_s1^beta_s1 +
                        A_w * (q_w * N_w1^beta_w1 * E1)^-f_w1 * q_w * N_w1^beta_w1 - (c))
    # Return the derivatives as a list
    return(list(c(dN_s1, dN_w1, dE1)))
  })
}

# Define the initial state and parameters
state <- c(N_s1 = 4, N_w1 = 2, E1 = 0.5)
parameters_1 <- c(q_s = 0.02, q_w = 0.02, k_s = 4, k_w = 2, r_s = 1, r_w = 0.99, alpha = 1,
                c = 0.05, A_w = 1, A_s = 1, beta_w1 = 1, beta_s1 = 1, f_w1 = 0, f_s1 = 0)

# Define the time interval and solve the ODEs
out1 <- ode(y = state, times = times, func = scenario_1, parms = parameters_1)

out1_df <- out1 %>% 
  as.data.frame() %>% 
  mutate(catch_s1 = q_s * N_s1^beta_s1 * E1,
         catch_w1 = q_w * N_w1^beta_w1 * E1,
         price_s1 = A_s * (q_s * N_s1^beta_s1 * E1)^-f_s1, 
         price_w1 = A_w * (q_w * N_w1^beta_w1 * E1)^-f_w1,
         cpue_s1 = catch_s1 / E1,
         cpue_w1 = catch_w1 / E1,
         cost1 = cost * E1,
         pi_sum1 = E1 * ((price_s1 * q_s * N_s1^beta_s1) + (price_w1 * q_w * N_w1^beta_w1) - cost)) %>% 
  pivot_longer(cols = dplyr::starts_with("N_"),
               names_to = "stock",
               values_to = "stock_size") %>% 
  pivot_longer(cols = dplyr::starts_with("E"),
               names_to = "effort",
               values_to = "effort_level") %>% 
  pivot_longer(cols = starts_with("catch_"),
               names_to = "stock_catch",
               values_to = "catch_size") %>% 
  pivot_longer(cols = starts_with("price_"),
               names_to = "stock_price",
               values_to = "price") %>% 
  pivot_longer(cols = starts_with("cpue_"),
               names_to = "stock_cpue",
               values_to = "cpue_level") %>% 
  pivot_longer(cols = starts_with("cost"),
               names_to = "cost_scenario",
               values_to = "cost") %>% 
  pivot_longer(cols = starts_with("pi_"),
               names_to = "stock_profit",
               values_to = "profit_level") %>% 
  mutate(scenario_id = "1") %>% 
  mutate(scenario_label = "None")

out1_stock <- out1_df %>% 
  select(time, stock, stock_size, scenario_label)

out1_effort <- out1_df %>% 
  select(time, effort, effort_level, scenario_label)

out1_catch <- out1_df %>% 
  select(time, stock_catch, catch_size, scenario_label)

out1_price <- out1_df %>% 
  select(time, stock_price, price, scenario_label)

out1_cpue <- out1_df %>% 
  select(time, stock_cpue, cpue_level, scenario_label)

out1_cost <- out1_df %>% 
  select(time, cost_scenario, cost, scenario_label)

out1_profit <- out1_df %>% 
  select(time, stock_profit, profit_level, scenario_label)

```

```{r}
# Define the function that calculates the derivatives
scenario_2 <- function(time, state, parameters) {
  with(as.list(c(state, parameters)), {
    
    # Calculate the derivatives
    dN_s2 <- r_s * N_s2 * (1 - (N_s2/k_s)) - (q_s * N_s2^beta_s2 * E2) 
    dN_w2 <- r_w * N_w2 * (1 - (N_w2/k_w)) - (q_w * N_w2^beta_w2 * E2) 
    dE2 <- alpha * E2 * (A_s * (q_s * N_s2^beta_s2 * E2)^-f_s2 * q_s * N_s2^beta_s2 +
                        A_w * (q_w * N_w2^beta_w2 * E2)^-f_w2 * q_w * N_w2^beta_w2 - (c))
    
    # Return the derivatives as a list
    return(list(c(dN_s2, dN_w2, dE2)))
  })
}

# Define the initial state and parameters
state2 <- c(N_s2 = 4, N_w2 = 2, E2 = 0.5)
parameters_2 <- c(q_s = 0.02, q_w = 0.02, k_s = 4, k_w = 2, r_s = 1, r_w = 0.99, alpha = 1,
                c = 0.05, A_w = 1, A_s = 1, beta_w2 = 1, beta_s2 = 0.56, f_w2 = 0, f_s2 = 0.22)


out2 <- ode(y = state2, times = times, func = scenario_2, parms = parameters_2)

out2_df <- out2 %>% 
  as.data.frame() %>% 
  mutate(catch_s2 = q_s * N_s2^beta_s2 * E2,
         catch_w2 = q_w * N_w2^beta_w2 * E2,
         price_s2 = A_s * (q_s * N_s2^beta_s2 * E2)^-f_s2,
         price_w2 = A_w * (q_w * N_w2^beta_w2 * E2)^-f_w2,
         cpue_s2 = catch_s2 / E2,
         cpue_w2 = catch_w2 / E2,
         cost2 = cost * E2,
         pi_sum2 = E2 * ((price_s2 * q_s * N_s2^beta_s2) + (price_w2 * q_w * N_w2^beta_w2) - cost)) %>% 
  pivot_longer(cols = dplyr::starts_with("N_"),
               names_to = "stock",
               values_to = "stock_size") %>% 
  pivot_longer(cols = dplyr::starts_with("E"),
               names_to = "effort",
               values_to = "effort_level") %>% 
  pivot_longer(cols = starts_with("catch_"),
               names_to = "stock_catch",
               values_to = "catch_size") %>% 
  pivot_longer(cols = starts_with("price_"),
               names_to = "stock_price",
               values_to = "price") %>% 
  pivot_longer(cols = starts_with("cpue_"),
               names_to = "stock_cpue",
               values_to = "cpue_level") %>% 
  pivot_longer(cols = starts_with("cost"),
               names_to = "cost_scenario",
               values_to = "cost") %>% 
  pivot_longer(cols = starts_with("pi_"),
               names_to = "stock_profit",
               values_to = "profit_level") %>% 
  mutate(scenario_id = "2") %>% 
  mutate(scenario_label = "Strong stock")

out2_stock <- out2_df %>% 
  select(time, stock, stock_size, scenario_label)

out2_effort <- out2_df %>% 
  select(time, effort, effort_level, scenario_label)

out2_catch <- out2_df %>% 
  select(time, stock_catch, catch_size, scenario_label)

out2_price <- out2_df %>% 
  select(time, stock_price, price, scenario_label)

out2_cpue <- out2_df %>% 
  select(time, stock_cpue, cpue_level,scenario_label)

out2_cost <- out2_df %>% 
  select(time, cost_scenario, cost, scenario_label)

out2_profit <- out2_df %>% 
  select(time, stock_profit, profit_level, scenario_label)

  
```



```{r}
# Define the function that calculates the derivatives
scenario_3 <- function(time, state, parameters) {
    with(as.list(c(state, parameters)), {

    # Calculate the derivatives
    if(N_w3 > 0) {
      dN_s3 <- r_s * N_s3 * (1 - N_s3/k_s) - (q_s * N_s3^beta_s3 * E3)
      dN_w3 <- r_w * N_w3 * (1 - N_w3/k_w) - (q_w * N_w3^beta_w3 * E3)
      dE3 <- alpha * E3 * (A_s * (q_s * N_s3^beta_s3 * E3)^-f_s3 * q_s * N_s3^beta_s3 +
                          A_w * (q_w * N_w3^beta_w3 * E3)^-f_w3 * q_w * N_w3^beta_w3 - (c))
    } else {
      dN_s3 <- r_s * N_s3 * (1 - N_s3/k_s) - (q_s * N_s3^beta_s3 * E3)
      dN_w3 <- 0
      dE3 <- alpha * E3 * (A_s * (q_s * N_s3^beta_s3 * E3)^-f_s3 * q_s * N_s3^beta_s3 - (c))
    }
    
    # Return the derivatives as a list
    return(list(c(dN_s3, dN_w3, dE3)))
      })
 }



# Define the initial state and parameters
state3 <- c(N_s3 = 4, N_w3 = 2, E3 = 0.5)
parameters_3 <- c(q_s = 0.02, q_w = 0.02, k_s = 4, k_w = 2, r_s = 1, r_w = 0.99, alpha = 1,
                c = 0.05, A_w = 1, A_s = 1, beta_w3 = 0.56, beta_s3 = 1, f_w3 = 0.22, f_s3 = 0)

out3 <- ode(y = state3, times = times, func = scenario_3, parms = parameters_3)

  
out3_df <- out3 %>% 
  as.data.frame() %>% 
  mutate(N_w3 = case_when(
    N_w3 < 0 ~ 0,
    TRUE ~ N_w3
  )) %>% 
  mutate(catch_s3 = q_s * N_s3^beta_s3 * E3,
         catch_w3 = q_w * N_w3^beta_w3 * E3,
         price_s3 = A_s * (q_s * N_s3^beta_s3 * E3)^-f_s3,
         price_w3 = A_w * (q_w * N_w3^beta_w3 * E3)^-f_w3,
         cpue_s3 = catch_s3 / E3,
         cpue_w3 = catch_w3 / E3,
         cost3 = cost * E3,
         pi_st3 = E3 * ((price_s3 * q_s * N_s3^beta_s3) - cost),
         pi_sum3 = E3 * ((price_s3 * q_s * N_s3^beta_s3) + (price_w3 * q_w * N_w3^beta_w3) - cost)) %>% 
  mutate_at(vars(price_w3), ~ replace(., is.infinite(.), 0)) %>% 
  mutate(pi_sum3 = ifelse(N_w3 > 0, pi_sum3, pi_st3)) %>% 
  pivot_longer(cols = dplyr::starts_with("N_"),
               names_to = "stock",
               values_to = "stock_size") %>% 
  pivot_longer(cols = dplyr::starts_with("E"),
               names_to = "effort",
               values_to = "effort_level") %>% 
  pivot_longer(cols = starts_with("catch_"),
               names_to = "stock_catch",
               values_to = "catch_size") %>% 
  pivot_longer(cols = starts_with("price_"),
               names_to = "stock_price",
               values_to = "price") %>% 
  pivot_longer(cols = starts_with("cpue_"),
               names_to = "stock_cpue",
               values_to = "cpue_level") %>% 
  pivot_longer(cols = starts_with("cost"),
               names_to = "cost_scenario",
               values_to = "cost") %>% 
  pivot_longer(cols = starts_with("pi_"),
               names_to = "stock_profit",
               values_to = "profit_level") %>% 
  mutate(scenario_id = "3") %>% 
  mutate(scenario_label = "Weak stock")

out3_stock <- out3_df %>% 
  select(time, stock, stock_size, scenario_label)

out3_effort <-out3_df %>% 
  select(time, effort, effort_level, scenario_label) 

out3_catch <- out3_df %>% 
  select(time, stock_catch, catch_size, scenario_label)

out3_price <- out3_df %>% 
  select(time, stock_price, price, scenario_label)

out3_cpue <- out3_df %>% 
  select(time, stock_cpue, cpue_level, scenario_label)

out3_cost <- out3_df %>% 
  select(time, cost_scenario, cost,scenario_label)

out3_profit <- out3_df %>% 
  select(time, stock_profit, profit_level, scenario_label)

```



```{r}
scenario_4 <- function(time, state, parameters) {
  with(as.list(c(state, parameters)), {
    
    # Calculate the derivatives
    if(N_w4 > 0){
    dN_s4 <- r_s * N_s4 * (1 - (N_s4/k_s)) - (q_s * N_s4^beta_s4 * E4) 
    dN_w4 <- r_w * N_w4 * (1 - (N_w4/k_w)) - (q_w * N_w4^beta_w4 * E4) 
    dE4 <- alpha * E4 * (A_s * (q_s * N_s4^beta_s4 * E4)^-f_s4 * q_s * N_s4^beta_s4 +
                        A_w * (q_w * N_w4^beta_w4 * E4)^-f_w4 * q_w * N_w4^beta_w4 - (c))
  
    } else {
      
      dN_s4 <- r_s * N_s4 * (1 - (N_s4/k_s)) - (q_s * N_s4^beta_s4 * E4)
      dN_w4 <- 0
      dE4 <- alpha * E4 * (A_s * (q_s * N_s4^beta_s4 * E4)^-f_s4 * q_s * N_s4^beta_s4 - (c))
      
    }
  
    # Return the derivatives as a list
    return(list(c(dN_s4, dN_w4, dE4))) #, dC_s1, dC_w1, dPi_w1, dPi_s1
  })
}

# Define the initial state and parameters
state4 <- c(N_s4 = 4, N_w4 = 2, E4 = 0.5)
parameters_4 <- c(q_s = 0.02, q_w = 0.02, k_s = 4, k_w = 2, r_s = 1, r_w = 0.99, alpha = 1,
                c = 0.05, A_w = 1, A_s = 1, beta_w4 = 0.56, beta_s4 = 0.56, f_w4 = 0.22, f_s4 = 0.22)

# Solve ODEs
out4 <- ode(y = state4, times = times, func = scenario_4, parms = parameters_4)

out4_df <- out4 %>% 
  as.data.frame() %>% 
  mutate(N_w4 = case_when(
    N_w4 < 0 ~ 0,
    TRUE ~ N_w4
  )) %>% 
  mutate(catch_s4 = q_s * N_s4^beta_s4 * E4,
         catch_w4 = q_w * N_w4^beta_w4 * E4,
         price_s4 = A_s * (q_s * N_s4^beta_s4 * E4)^-f_s4,
         price_w4 = A_w * (q_w * N_w4^beta_w4 * E4)^-f_w4,
         cpue_s4 = catch_s4 / E4,
         cpue_w4 = catch_w4 / E4,
         cost4 = cost * E4,
         pi_st4 = E4 * ((price_s4 * q_s * N_s4^beta_s4) - cost),
         pi_sum4 = E4 * ((price_s4 * q_s * N_s4^beta_s4) + (price_w4 * q_w * N_w4^beta_w4) - cost)) %>% 
  mutate_at(vars(price_w4), ~ replace(., is.infinite(.), 0)) %>% 
  mutate(pi_sum4 = ifelse(N_w4 > 0, pi_sum4, pi_st4)) %>% 
  pivot_longer(cols = dplyr::starts_with("N_"),
               names_to = "stock",
               values_to = "stock_size") %>% 
  pivot_longer(cols = dplyr::starts_with("E"),
               names_to = "effort",
               values_to = "effort_level") %>% 
  pivot_longer(cols = starts_with("catch_"),
               names_to = "stock_catch",
               values_to = "catch_size") %>% 
  pivot_longer(cols = starts_with("price_"),
               names_to = "stock_price",
               values_to = "price") %>% 
  pivot_longer(cols = starts_with("cpue_"),
               names_to = "stock_cpue",
               values_to = "cpue_level") %>% 
  pivot_longer(cols = starts_with("cost"),
               names_to = "cost_scenario",
               values_to = "cost") %>% 
  pivot_longer(cols = starts_with("pi_"),
               names_to = "stock_profit",
               values_to = "profit_level") %>% 
  mutate(scenario_id = "4") %>% 
  mutate(scenario_label = "Both stocks")

out4_stock <- out4_df %>% 
  select(time, stock, stock_size, scenario_label)

out4_effort <- out4_df %>% 
  select(time, effort, effort_level, scenario_label)

out4_catch <- out4_df %>% 
  select(time, stock_catch, catch_size, scenario_label)

out4_price <- out4_df %>% 
  select(time, stock_price, price, scenario_label)

out4_cpue <- out4_df %>% 
  select(time, stock_cpue, cpue_level, scenario_label)

out4_cost <- out4_df %>% 
  select(time, cost_scenario, cost, scenario_label)

out4_profit <- out4_df %>% 
  select(time, stock_profit, profit_level, scenario_label)

```

```{r}
# create subsets of variable data outputs for all sub-scenarios 
## stock size
out_stock_join <- bind_rows(out1_stock, out2_stock, out3_stock, out4_stock) %>%
  mutate(b_v_k = case_when(
    str_detect(stock, "N_s") ~ stock_size/k_s,
    str_detect(stock, "N_w") ~ stock_size/k_w
  )) %>% 
  mutate(stock = case_when(
    str_detect(stock, "N_s") ~ "Strong stock",
    str_detect(stock, "N_w") ~ "Weak stock"
  )) %>% 
  distinct()

write_csv(out_stock_join, file = file.path(outdir, "stock_sim.csv"), col_names = TRUE)

## fishing effort
out_effort_join <- bind_rows(out1_effort, out2_effort, out3_effort, out4_effort) %>% 
  distinct()

write_csv(out_effort_join, file = file.path(outdir, "effort_sim.csv"), col_names = TRUE)

## catch
out_catch_join <- bind_rows(out1_catch, out2_catch, out3_catch, out4_catch) %>% 
  mutate(stock_catch = case_when(
    str_detect(stock_catch, "_s") ~ "Strong stock",
    str_detect(stock_catch, "_w") ~ "Weak stock"
  )) %>% 
  distinct()

write_csv(out_catch_join, file = file.path(outdir, "catch_sim2.csv"), col_names = TRUE)

## price
out_price_join <- bind_rows(out1_price, out2_price, out3_price, out4_price) %>%  
  mutate(stock_price = case_when(
    str_detect(stock_price, "_s") ~ "Strong stock",
    str_detect(stock_price, "_w") ~ "Weak stock"
  )) %>% 
  distinct()

write_csv(out_price_join, file = file.path(outdir, "price_sim.csv"), col_names = TRUE)


## CPUE
out_cpue_join <- bind_rows(out1_cpue, out2_cpue, out3_cpue, out4_cpue) %>% 
  mutate(stock_cpue = case_when(
    str_detect(stock_cpue, "_s") ~ "Strong stock",
    str_detect(stock_cpue, "_w") ~ "Weak stock"
  )) %>% 
  distinct()

write_csv(out_cpue_join, file = file.path(outdir, "cpue_sim.csv"), col_names = TRUE)

## profits
out_profit_join <- bind_rows(out1_profit, out2_profit, out3_profit, out4_profit)  %>% 
  mutate(stock_profit = case_when(
    str_detect(stock_profit, "_st") ~ "Strong stock",
    str_detect(stock_profit, "_sum") ~ "Profit"
  )) %>% 
  filter(stock_profit %in% c("Profit")) %>% 
  distinct()

write_csv(out_profit_join, file = file.path(outdir, "profit_sim.csv"), col_names = TRUE)
```























