---
title: "differential_equation_test"
author: "Leonardo Feitosa"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(deSolve)
library(patchwork)
library(janitor)

basedir <- "G:/Meu Drive/PhD Project - Fisheries bycatch/Bycatch project/Chapter 1 - Simulation model/analyses/"
outdir <- file.path(basedir, "model_outs") # calls present data from raster files
```

```{r}
# define general parameters
cost <- 0.05
alpha <- 1
A_w <- 1
A_s <- 1
q_s1 <- 0.02
q_w1 <- 0.01
q_s2 <- 0.01
q_w2 <- 0.02
k_s <- 4
k_w <- 2
r_s <- 1
r_w <- 0.67

# define parameters that switch per scenario
beta_s1 <- 1
beta_s2 <- 0.56
beta_s3 <- 1
beta_s4 <- 0.56

beta_w1 <- 1
beta_w2 <- 1
beta_w3 <- 0.56
beta_w4 <- 0.56

f_s1 <- 0 
f_s2 <- 0.22
f_s3 <- 0
f_s4 <- 0.22

f_w1 <- 0
f_w2 <- 0
f_w3 <- 0.22
f_w4 <- 0.22

# time steps
times <- seq(0, 500, by = .1)
```

```{r}
# Define the function that calculates the derivatives
scenario_1 <- function(time, state, parameters) {
  with(as.list(c(state, parameters)), {
    if(N_w1 > 0){
    # Calculate the derivatives
    dN_s1 <- N_s1 * (r_s * (1 - (N_s1/k_s))) - (q_s1 * (N_s1^beta_s1) * E1_A) - (q_s2 * (N_s1^beta_s1) * E1_B)   
    dN_w1 <- N_w1 * (r_w * (1 - (N_w1/k_w))) - (q_w1 * (N_w1^beta_w1) * E1_A) - (q_w2 * (N_w1^beta_w1) * E1_B)  
    dE1_A <- alpha * E1_A * ((A_s * (q_s1 * (N_s1^beta_s1) * E1_A)^-f_s1) * q_s1 * (N_s1^beta_s1) +
                        (A_w * (q_w1 * (N_w1^beta_w1) * E1_A)^-f_w1) * q_w1 * (N_w1^beta_w1) - (c))
    dE1_B <- alpha * E1_B * ((A_s * (q_s2 * (N_s1^beta_s1) * E1_B)^-f_s1) * q_s2 * (N_s1^beta_s1) +
                        (A_w * (q_w2 * (N_w1^beta_w1) * E1_B)^-f_w1) * q_w2 * (N_w1^beta_w1) - (c))
    } else {
      dN_s1 <- r_s * N_s1 * (1 - (N_s1/k_s)) - (q_s1 * (N_s1^beta_s1) * E1_A) - (q_w1 * (N_s1^beta_s1) * E1_B)   
      dN_w1 <- 0
      dE1_A <- alpha * E1_A * ((A_s * (q_s1 * (N_s1^beta_s1) * E1_A)^-f_s1) * q_s1 * (N_s1^beta_s1) - (c))
      dE1_B <- alpha * E1_B * ((A_s * (q_s1 * (N_s1^beta_s1) * E1_B)^-f_s1) * q_s1 * (N_s1^beta_s1) - (c))
    }
    # Return the derivatives as a list
    return(list(c(dN_s1, dN_w1, dE1_A, dE1_B)))
  })
}

# Define the initial state and parameters
state <- c(N_s1 = 4, N_w1 = 2, E1_A = 0.01, E1_B = 0.01)
parameters_1 <- c(q_s1 = 0.02, q_w1 = 0.01, q_s2 = 0.01, q_w2 = 0.02, k_s = 4, k_w = 2, r_s = 1, r_w = 0.67, alpha = 1,
                c = 0.05, A_w = 1, A_s = 1, beta_w1 = 1, beta_s1 = 1, f_w1 = 0, f_s1 = 0)

# Define the time interval and solve the ODEs
out1 <- ode(y = state, times = times, func = scenario_1, parms = parameters_1)

out1_df <- out1 %>% 
  as.data.frame() %>% 
  mutate(N_w1 = case_when(
    N_w1 < 0 ~ 0,
    TRUE ~ N_w1
  )) %>% 
  mutate(catch_s1 = (q_s1 * (N_s1^beta_s1) * E1_A) + (q_s2 * (N_s1^beta_s1) * E1_B),
         catch_w1 = (q_w1 * (N_w1^beta_w1) * E1_A) + (q_w2 * (N_w1^beta_w1) * E1_B),
         cpue_s1 = catch_s1 / (E1_A + E1_B),
         cpue_w1 = catch_w1 / (E1_A + E1_B),
         cost1_A = cost * E1_A,
         cost1_B = cost * E1_B,
         price_s1 = (A_s * (q_s1 * (N_s1^beta_s1) * E1_A)^-f_s1) + (A_s * (q_s2 * (N_s1^beta_s1) * E1_B)^-f_s1),
         price_w1 = (A_w * (q_w1 * (N_w1^beta_w1) * E1_A)^-f_w1) + (A_w * (q_w2 * (N_w1^beta_w1) * E1_B)^-f_w1),
         pi_sum1_A = E1_A * ((price_s1 * q_s1 * (N_s1^beta_s1)) + (price_w1 * q_s2 * (N_w1^beta_w1)) - cost),
         pi_sum1_B = E1_B * ((price_w1 * q_w1 * (N_w1^beta_w1)) + (price_s1 * q_w2 * (N_w1^beta_w1)) - cost),
         pi_sum1 = pi_sum1_A + pi_sum1_B) %>% 
  pivot_longer(cols = dplyr::starts_with("N_"),
               names_to = "stock",
               values_to = "stock_size") %>% 
  pivot_longer(cols = dplyr::starts_with("E"),
               names_to = "effort",
               values_to = "effort_level") %>% 
  pivot_longer(cols = starts_with("catch_"),
               names_to = "stock_catch",
               values_to = "catch_size") %>% 
  pivot_longer(cols = starts_with("price_"),
               names_to = "stock_price",
               values_to = "price") %>% 
  pivot_longer(cols = starts_with("cpue_"),
               names_to = "stock_cpue",
               values_to = "cpue_level") %>% 
  pivot_longer(cols = starts_with("cost"),
               names_to = "cost_scenario",
               values_to = "cost") %>% 
  pivot_longer(cols = starts_with("pi_"),
               names_to = "stock_profit",
               values_to = "profit_level") %>% 
  mutate(scenario_id = "1") %>% 
  mutate(scenario_label = "None")

out1_stock <- out1_df %>% 
  select(time, stock, stock_size, scenario_label) %>% 
  distinct()

out1_effort <- out1_df %>% 
  select(time, effort, effort_level, scenario_label)%>% 
  distinct()

out1_catch <- out1_df %>% 
  select(time, stock_catch, catch_size, scenario_label)%>% 
  distinct()

out1_price <- out1_df %>% 
  select(time, stock_price, price, scenario_label)%>% 
  distinct()

out1_cpue <- out1_df %>% 
  select(time, stock_cpue, cpue_level, scenario_label) %>% 
  distinct()
out1_cost <- out1_df %>% 
  select(time, cost_scenario, cost, scenario_label) %>% 
  distinct()

out1_profit <- out1_df %>% 
  select(time, stock_profit, profit_level, scenario_label) %>% 
  distinct()

```

```{r}
ggplot() +
  geom_line(data = out1_stock, 
            aes(x = time, y = stock_size, color = stock)) +
  geom_line(data = out1_effort, 
            aes(x = time, y = effort_level, color = effort)) +
  scale_y_continuous(limits = c(0, 30),
                     breaks = seq(0, 30, 5))

# ggplot() +
#   geom_line(data = out1_price, 
#             aes(x = time, y = price, color = stock_price)) +
#   geom_line(data = out1_profit, 
#             aes(x = time, y = profit_level, color = stock_profit))
```


```{r}
# Define the function that calculates the derivatives
scenario_2 <- function(time, state, parameters) {
  with(as.list(c(state, parameters)), {
    if(N_w2 > 0){
    # Calculate the derivatives
    dN_s2 <- N_s2 * (r_s * (1 - (N_s2/k_s))) - (q_s1 * (N_s2^beta_s2) * E2_A) - (q_s2 * (N_s2^beta_s2) * E2_B)   
    dN_w2 <- N_w2 * (r_w * (1 - (N_w2/k_w))) - (q_w1 * (N_w2^beta_w2) * E2_A) - (q_w2 * (N_w2^beta_w2) * E2_B)  
    dE2_A <- alpha * E2_A * ((A_s * (q_s1 * (N_s2^beta_s2) * E2_A)^-f_s2) * q_s1 * (N_s2^beta_s2) +
                             (A_w * (q_w1 * (N_w2^beta_w2) * E2_A)^-f_w2) * q_w1 * (N_w2^beta_w2) - (c))
    dE2_B <- alpha * E2_B * ((A_s * (q_s2 * (N_s2^beta_s2) * E2_B)^-f_s2) * q_s2 * (N_s2^beta_s2) +
                             (A_w * (q_w2 * (N_w2^beta_w2) * E2_B)^-f_w2) * q_w2 * (N_w2^beta_w2) - (c))
    } else {
      dN_s2 <- r_s * N_s2 * (1 - (N_s2/k_s)) - (q_s1 * (N_s2^beta_s2) * E2_A) - (q_w1 * (N_s2^beta_s2) * E2_B)   
      dN_w2 <- 0
      dE2_A <- alpha * E2_A * ((A_s * (q_s1 * (N_s2^beta_s2) * E2_A)^-f_s2) * q_s1 * (N_s2^beta_s2) - (c))
      dE2_B <- alpha * E2_B * ((A_s * (q_s1 * (N_s2^beta_s2) * E2_B)^-f_s2) * q_s1 * (N_s2^beta_s2) - (c))
    }
    # Return the derivatives as a list
    return(list(c(dN_s2, dN_w2, dE2_A, dE2_B)))
  })
}

# Define the initial state and parameters
state2 <- c(N_s2 = 4, N_w2 = 2, E2_A = 0.01, E2_B = 0.01)
parameters_2 <- c(q_s1 = 0.02, q_w1 = 0.01, q_s2 = 0.01, q_w2 = 0.02, k_s = 4, k_w = 2, r_s = 1, r_w = 0.67, alpha = 1,
                c = 0.05, A_w = 1, A_s = 1, beta_w2 = 1, beta_s2 = 0.56, f_w2 = 0.22, f_s2 = 0.22)


out2 <- ode(y = state2, times = times, func = scenario_2, parms = parameters_2)

out2_df <- out2 %>% 
  as.data.frame() %>% 
  mutate(N_w2 = case_when(
    N_w2 < 0 ~ 0,
    TRUE ~ N_w2
  )) %>% 
  mutate(catch_s2 = (q_s1 * (N_s2^beta_s2) * E2_A) + (q_s2 * (N_s2^beta_s2) * E2_B),
         catch_w2 = (q_w1 * (N_w2^beta_w2) * E2_A) + (q_w2 * (N_w2^beta_w2) * E2_B),
         cpue_s2 = catch_s2 / (E2_A + E2_B),
         cpue_w2 = catch_w2 / (E2_A + E2_B),
         cost2_A = cost * E2_A,
         cost2_B = cost * E2_B,
         price_s2 = (A_s * (q_s1 * (N_s2^beta_s2) * E2_A)^-f_s2) + (A_s * (q_s2 * (N_s2^beta_s2) * E2_B)^-f_s2),
         price_w2 = (A_w * (q_w1 * (N_w2^beta_w2) * E2_A)^-f_w2) + (A_w * (q_w2 * (N_w2^beta_w2) * E2_B)^-f_w2),
         pi_sum2_A = E2_A * ((price_s2 * q_s1 * (N_s2^beta_s2)) + (price_w2 * q_s2 * (N_w2^beta_w2)) - cost),
         pi_sum2_B = E2_B * ((price_w2 * q_w1 * (N_w2^beta_w2)) + (price_s2 * q_w2 * (N_w2^beta_w2)) - cost),
         pi_sum2 = pi_sum2_A + pi_sum2_B) %>% 
  pivot_longer(cols = dplyr::starts_with("N_"),
               names_to = "stock",
               values_to = "stock_size") %>% 
  pivot_longer(cols = dplyr::starts_with("E"),
               names_to = "effort",
               values_to = "effort_level") %>% 
  pivot_longer(cols = starts_with("catch_"),
               names_to = "stock_catch",
               values_to = "catch_size") %>% 
  pivot_longer(cols = starts_with("price_"),
               names_to = "stock_price",
               values_to = "price") %>% 
  pivot_longer(cols = starts_with("cpue_"),
               names_to = "stock_cpue",
               values_to = "cpue_level") %>% 
  pivot_longer(cols = starts_with("cost"),
               names_to = "cost_scenario",
               values_to = "cost") %>% 
  pivot_longer(cols = starts_with("pi_"),
               names_to = "stock_profit",
               values_to = "profit_level") %>% 
  mutate(scenario_id = "2") %>% 
  mutate(scenario_label = "Strong stock")

out2_stock <- out2_df %>% 
  select(time, stock, stock_size, scenario_label) %>% 
  distinct()

out2_effort <- out2_df %>% 
  select(time, effort, effort_level, scenario_label) %>% 
  distinct()

out2_catch <- out2_df %>% 
  select(time, stock_catch, catch_size, scenario_label)%>% 
  distinct()

out2_price <- out2_df %>% 
  select(time, stock_price, price, scenario_label)%>% 
  distinct()

out2_cpue <- out2_df %>% 
  select(time, stock_cpue, cpue_level, scenario_label)%>% 
  distinct()

out2_cost <- out2_df %>% 
  select(time, cost_scenario, cost, scenario_label)%>% 
  distinct()

out2_profit <- out2_df %>% 
  select(time, stock_profit, profit_level, scenario_label)%>% 
  distinct()

```

```{r}
ggplot() +
  geom_line(data = out2_stock, 
            aes(x = time, y = stock_size, color = stock)) +
  geom_line(data = out2_effort, 
            aes(x = time, y = effort_level, color = effort))
```


```{r}
# Define the function that calculates the derivatives
scenario_3 <- function(time, state, parameters) {
  with(as.list(c(state, parameters)), {
    if(N_w3 > 0){
      # Calculate derivatives
    dN_s3 <- N_s3 * (r_s * (1 - (N_s3/k_s))) - (q_s1 * (N_s3^beta_s3) * E3_A) - (q_s2 * (N_s3^beta_s3) * E3_B)   
    dN_w3 <- N_w3 * (r_w * (1 - (N_w3/k_w))) - (q_w1 * (N_w3^beta_w3) * E3_A) - (q_w2 * (N_w3^beta_w3) * E3_B)  
    dE3_A <- alpha * E3_A * ((A_s * (q_s1 * (N_s3^beta_s3) * E3_A)^-f_s3) * q_s1 * (N_s3^beta_s3) +
                        (A_w * (q_w1 * (N_w3^beta_w3) * E3_A)^-f_w3) * q_w1 * (N_w3^beta_w3) - (c))
    dE3_B <- alpha * E3_B * ((A_s * (q_s2 * (N_s3^beta_s3) * E3_B)^-f_s3) * q_s2 * (N_s3^beta_s3) +
                        (A_w * (q_w2 * (N_w3^beta_w3) * E3_B)^-f_w3) * q_w2 * (N_w3^beta_w3) - (c))
    } else {
      dN_s3 <- r_s * N_s3 * (1 - (N_s3/k_s)) - (q_s1 * (N_s3^beta_s3) * E3_A) - (q_w1 * (N_s3^beta_s3) * E3_B)   
      dN_w3 <- 0
      #dE3_A <- alpha * E3_A * ((A_s * (q_s1 * (N_s3^beta_s3) * E3_A)^-f_s3) * q_s1 * (N_s3^beta_s3) - (c))
      #dE3_B <- alpha * E3_B * ((A_s * (q_s1 * (N_s3^beta_s3) * E3_B)^-f_s3) * q_s1 * (N_s3^beta_s3) - (c))
    }
    # Return the derivatives as a list
    return(list(c(dN_s3, dN_w3, dE3_A, dE3_B)))
  })
}

# Define the initial state and parameters
state3 <- c(N_s3 = 4, N_w3 = 2, E3_A = 0.01, E3_B = 0.01)
parameters_3 <- c(q_s1 = 0.02, q_w1 = 0.01, q_s2 = 0.01, q_w2 = 0.02, k_s = 4, k_w = 2, r_s = 1, r_w = 0.67, alpha = 1,
                c = 0.05, A_w = 1, A_s = 1, beta_w3 = 0.56, beta_s3 = 1, f_w3 = 0.22, f_s3 = 0.22)

out3 <- ode(y = state3, times = times, func = scenario_3, parms = parameters_3)

  
out3_df <- out3 %>% 
  as.data.frame() %>% 
  mutate(N_w3 = case_when(
    N_w3 < 0 ~ 0,
    TRUE ~ N_w3
  )) %>% 
  mutate(catch_s3 = (q_s1 * (N_s3^beta_s3) * E3_A) + (q_s2 * (N_s3^beta_s3) * E3_B),
         catch_w3 = (q_w1 * (N_w3^beta_w3) * E3_A) + (q_w2 * (N_w3^beta_w3) * E3_B),
         cpue_s3 = catch_s3 / (E3_A + E3_B),
         cpue_w3 = catch_w3 / (E3_A + E3_B),
         cost3_A = cost * E3_A,
         cost3_B = cost * E3_B,
         price_s3 = (A_s * (q_s1 * (N_s3^beta_s3) * E3_A)^-f_s3) + (A_s * (q_s2 * (N_s3^beta_s3) * E3_B)^-f_s3),
         price_w3 = (A_w * (q_w1 * (N_w3^beta_w3) * E3_A)^-f_w3) + (A_w * (q_w2 * (N_w3^beta_w3) * E3_B)^-f_w3),
         pi_st3_A = E3_A * ((price_s3 * q_s1 * (N_s3^beta_s3))  - cost),
         pi_st3_B = E3_B * ((price_s3 * q_s2 * (N_s3^beta_s3))  - cost),
         pi_sum3_A = E3_A * ((price_s3 * q_s1 * (N_s3^beta_s3)) + (price_w3 * q_s2 * (N_w3^beta_w3)) - cost),
         pi_sum3_B = E3_B * ((price_w3 * q_w1 * (N_w3^beta_w3)) + (price_s3 * q_w2 * (N_w3^beta_w3)) - cost),
         pi_sum3 = pi_sum3_A + pi_sum3_B) %>% 
  mutate_at(vars(price_w3), ~ replace(., is.infinite(.), 0)) %>% 
  mutate(pi_sum3_A = ifelse(N_w3 > 0, pi_sum3_A, pi_st3_A),
         pi_sum3_B = ifelse(N_w3 > 0, pi_sum3_B, pi_st3_B),
         pi_sum3 = pi_sum3_A + pi_sum3_B) %>% 
  pivot_longer(cols = dplyr::starts_with("N_"),
               names_to = "stock",
               values_to = "stock_size") %>% 
  pivot_longer(cols = dplyr::starts_with("E"),
               names_to = "effort",
               values_to = "effort_level") %>% 
  pivot_longer(cols = starts_with("catch_"),
               names_to = "stock_catch",
               values_to = "catch_size") %>% 
  pivot_longer(cols = starts_with("price_"),
               names_to = "stock_price",
               values_to = "price") %>% 
  pivot_longer(cols = starts_with("cpue_"),
               names_to = "stock_cpue",
               values_to = "cpue_level") %>% 
  pivot_longer(cols = starts_with("cost"),
               names_to = "cost_scenario",
               values_to = "cost") %>% 
  pivot_longer(cols = starts_with("pi_"),
               names_to = "stock_profit",
               values_to = "profit_level") %>% 
  mutate(scenario_id = "3") %>% 
  mutate(scenario_label = "Weak stock")

out3_stock <- out3_df %>% 
  select(time, stock, stock_size, scenario_label)%>% 
  distinct()

out3_effort <-out3_df %>% 
  select(time, effort, effort_level, scenario_label) %>% 
  distinct()

out3_catch <- out3_df %>% 
  select(time, stock_catch, catch_size, scenario_label)%>% 
  distinct()

out3_price <- out3_df %>% 
  select(time, stock_price, price, scenario_label)%>% 
  distinct()

out3_cpue <- out3_df %>% 
  select(time, stock_cpue, cpue_level, scenario_label)%>% 
  distinct()

out3_cost <- out3_df %>% 
  select(time, cost_scenario, cost,scenario_label)%>% 
  distinct()

out3_profit <- out3_df %>% 
  select(time, stock_profit, profit_level, scenario_label)%>% 
  distinct()

```

```{r}
ggplot() +
  geom_line(data = out3_stock, 
            aes(x = time, y = stock_size, color = stock)) +
  geom_line(data = out3_effort, 
            aes(x = time, y = effort_level, color = effort))
```


```{r}
scenario_4 <- function(time, state, parameters) {
  with(as.list(c(state, parameters)), {
    if(N_w4 > 0){
    # Calculate the derivatives
    dN_s4 <- N_s4 * (r_s * (1 - (N_s4/k_s))) - (q_s1 * (N_s4^beta_s4) * E4_A) - (q_s2 * (N_s4^beta_s4) * E4_B)   
    dN_w4 <- N_w4 * (r_w * (1 - (N_w4/k_w))) - (q_w1 * (N_w4^beta_w4) * E4_A) - (q_w2 * (N_w4^beta_w4) * E4_B)  
    dE4_A <- alpha * E4_A * ((A_s * (q_s1 * (N_s4^beta_s4) * E4_A)^-f_s4) * q_s1 * (N_s4^beta_s4) +
                             (A_w * (q_w1 * (N_w4^beta_w4) * E4_A)^-f_w4) * q_w1 * (N_w4^beta_w4) - (c))
    dE4_B <- alpha * E4_B * ((A_s * (q_s2 * (N_s4^beta_s4) * E4_B)^-f_s4) * q_s2 * (N_s4^beta_s4) +
                             (A_w * (q_w2 * (N_w4^beta_w4) * E4_B)^-f_w4) * q_w2 * (N_w4^beta_w4) - (c))
    } else {
     dN_s4 <- r_s * N_s4 * (1 - (N_s4/k_s)) - (q_s1 * (N_s4^beta_s4) * E4_A) - (q_w1 * (N_s4^beta_s4) * E4_B)   
     dN_w4 <- 0
     dE4_A <- alpha * E4_A * ((A_s * (q_s1 * (N_s4^beta_s4) * E4_A)^-f_s4) * q_s1 * (N_s4^beta_s4) - (c))
     dE4_B <- alpha * E4_B * ((A_s * (q_s1 * (N_s4^beta_s4) * E4_B)^-f_s4) * q_s1 * (N_s4^beta_s4) - (c))
    }
    # Return the derivatives as a list
    return(list(c(dN_s4, dN_w4, dE4_A, dE4_B)))
  })

}

# Define the initial state and parameters
state4 <- c(N_s4 = 4, N_w4 = 2, E4_A = 0.5, E4_B = 0.5)
parameters_4 <- c(q_s1 = 0.02, q_w1 = 0.01, q_s2 = 0.01, q_w2 = 0.02, k_s = 4, k_w = 2, r_s = 1, r_w = 0.67, alpha = 1,
                c = 0.05, A_w = 1, A_s = 1, beta_w4 = 0.56, beta_s4 = 0.56, f_w4 = 0.22, f_s4 = 0.22)

# Solve ODEs
out4 <- ode(y = state4, times = times, func = scenario_4, parms = parameters_4)

out4_df <- out4 %>% 
  as.data.frame() %>% 
  mutate(N_w4 = case_when(
    N_w4 < 0 ~ 0,
    TRUE ~ N_w4
  )) %>% 
  mutate(catch_s4 = (q_s1 * (N_s4^beta_s4) * E4_A) + (q_s2 * (N_s4^beta_s4) * E4_B),
         catch_w4 = (q_w1 * (N_w4^beta_w4) * E4_A) + (q_w2 * (N_w4^beta_w4) * E4_B),
         cpue_s4 = catch_s4 / (E4_A + E4_B),
         cpue_w4 = catch_w4 / (E4_A + E4_B),
         cost4_A = cost * E4_A,
         cost4_B = cost * E4_B,
         price_s4 = (A_s * (q_s1 * (N_s4^beta_s4) * E4_A)^-f_s4) + (A_s * (q_s2 * (N_s4^beta_s4) * E4_B)^-f_s4),
         price_w4 = (A_w * (q_w1 * (N_w4^beta_w4) * E4_A)^-f_w4) + (A_w * (q_w2 * (N_w4^beta_w4) * E4_B)^-f_w4),
         pi_st4_A = E4_A * ((price_s4 * q_s1 * (N_s4^beta_s4))  - cost),
         pi_st4_B = E4_B * ((price_s4 * q_s2 * (N_s4^beta_s4))  - cost),
         pi_sum4_A = E4_A * ((price_s4 * q_s1 * (N_s4^beta_s4)) + (price_w4 * q_s2 * (N_w4^beta_w4)) - cost),
         pi_sum4_B = E4_B * ((price_w4 * q_w1 * (N_w4^beta_w4)) + (price_s4 * q_w2 * (N_w4^beta_w4)) - cost)) %>% 
  mutate_at(vars(price_w4), ~ replace(., is.infinite(.), 0)) %>% 
  mutate(pi_sum4_A = ifelse(N_w4 > 0, pi_sum4_A, pi_st4_A),
         pi_sum4_B = ifelse(N_w4 > 0, pi_sum4_B, pi_st4_B),
         pi_sum4 = pi_sum4_A + pi_sum4_B) %>%  
  pivot_longer(cols = dplyr::starts_with("N_"),
               names_to = "stock",
               values_to = "stock_size") %>% 
  pivot_longer(cols = dplyr::starts_with("E"),
               names_to = "effort",
               values_to = "effort_level") %>% 
  pivot_longer(cols = starts_with("catch_"),
               names_to = "stock_catch",
               values_to = "catch_size") %>% 
  pivot_longer(cols = starts_with("price_"),
               names_to = "stock_price",
               values_to = "price") %>% 
  pivot_longer(cols = starts_with("cpue_"),
               names_to = "stock_cpue",
               values_to = "cpue_level") %>% 
  pivot_longer(cols = starts_with("cost"),
               names_to = "cost_scenario",
               values_to = "cost") %>% 
  pivot_longer(cols = starts_with("pi_"),
               names_to = "stock_profit",
               values_to = "profit_level") %>% 
  mutate(scenario_id = "4") %>% 
  mutate(scenario_label = "Both stocks")

out4_stock <- out4_df %>% 
  select(time, stock, stock_size, scenario_label) %>% 
  distinct()

out4_effort <- out4_df %>% 
  select(time, effort, effort_level, scenario_label) %>% 
  distinct()

out4_catch <- out4_df %>% 
  select(time, stock_catch, catch_size, scenario_label) %>% 
  distinct()

out4_price <- out4_df %>% 
  select(time, stock_price, price, scenario_label) %>% 
  distinct()

out4_cpue <- out4_df %>% 
  select(time, stock_cpue, cpue_level, scenario_label) %>% 
  distinct()

out4_cost <- out4_df %>% 
  select(time, cost_scenario, cost, scenario_label)%>% 
  distinct()

out4_profit <- out4_df %>% 
  select(time, stock_profit, profit_level, scenario_label) %>% 
  distinct() %>% 
  filter(stock_profit == "pi_sum4")

```

```{r, fig.height=10, include = FALSE}
stock <- 
  ggplot() +
  geom_line(data = out4_stock, 
            aes(x = time, y = stock_size, color = stock)) 
effort <- 
  ggplot() +
  geom_line(data = out4_effort, 
            aes(x = time, y = effort_level, color = effort))
price <-
  ggplot() +
  geom_line(data = out4_price,
            aes(x = time, y = price, color = stock_price)) 

profit <- 
  ggplot() +
  geom_line(data = out4_profit %>% 
              filter(stock_profit == "pi_sum4"),
            aes(x = time, y = profit_level, color = stock_profit)) 

stock /
  effort /
  price / 
  profit &
  theme(legend.position = "none")
```


```{r}
# create subsets of variable data outputs for all sub-scenarios 
## stock size
out_stock_join <- bind_rows(out1_stock, out2_stock, out3_stock, out4_stock) %>%
  mutate(b_v_k = case_when(
    str_detect(stock, "N_s") ~ stock_size/k_s,
    str_detect(stock, "N_w") ~ stock_size/k_w
  )) %>% 
  mutate(stock = case_when(
    str_detect(stock, "N_s") ~ "Strong stock",
    str_detect(stock, "N_w") ~ "Weak stock"
  ))

#write_csv(out_stock_join, file = file.path(outdir, "stock_sim.csv"), col_names = TRUE)

## fishing effort
out_effort_join <- bind_rows(out1_effort, out2_effort, out3_effort, out4_effort) 

#write_csv(out_effort_join, file = file.path(outdir, "effort_sim.csv"), col_names = TRUE)

## catch
out_catch_join <- bind_rows(out1_catch, out2_catch, out3_catch, out4_catch) %>% 
  mutate(stock_catch = case_when(
    str_detect(stock_catch, "_s") ~ "Strong stock",
    str_detect(stock_catch, "_w") ~ "Weak stock"
  ))

#write_csv(out_catch_join, file = file.path(outdir, "catch_sim.csv"), col_names = TRUE)

## price
out_price_join <- bind_rows(out1_price, out2_price, out3_price, out4_price) %>%  
  mutate(stock_price = case_when(
    str_detect(stock_price, "_s") ~ "Strong stock",
    str_detect(stock_price, "_w") ~ "Weak stock"
  )) %>% 
  distinct()

#write_csv(out_price_join, file = file.path(outdir, "price_sim.csv"), col_names = TRUE)


## CPUE
out_cpue_join <- bind_rows(out1_cpue, out2_cpue, out3_cpue, out4_cpue) %>% 
  mutate(stock_cpue = case_when(
    str_detect(stock_cpue, "_s") ~ "Strong stock",
    str_detect(stock_cpue, "_w") ~ "Weak stock"
  ))

#write_csv(out_cpue_join, file = file.path(outdir, "cpue_sim.csv"), col_names = TRUE)

## profits
out_profit_join <- bind_rows(out1_profit, out2_profit, out3_profit, out4_profit) %>% 
  filter(stock_profit %in% c("pi_sum1", "pi_sum2", "pi_sum3", "pi_sum4"))

#write_csv(out_profit_join, file = file.path(outdir, "profit_sim.csv"), col_names = TRUE)
```


```{r create stock plots, fig.width=8}
# Creating mock up dataframe to add within-plot tags

tag_text <- data.frame(time = c(480, 480, 480, 480), 
                       b_v_k = c(0.94, 0.94, 0.94, 0.94),
                       label = c("A", "B", "C", "D"),
                       scenario_label = c("None",
                                          "Strong stock",
                                          "Weak stock",
                                          "Both stocks"))
b_v_k_plot <- 
  ggplot() +
  geom_hline(yintercept = 0.5,
              linetype = "dashed",
              color = "grey40",
              alpha = 0.8) +
  geom_hline(yintercept = 0.25,
              linetype = "dotted",
              color = "grey40",
              alpha = 0.8) +
  geom_line(data = out_stock_join, 
            aes(x = time, y = b_v_k, color = stock),
            linewidth = .8,
            alpha = .8,
            show.legend = T) +
  geom_text(data = tag_text,
            aes(x = time, y = b_v_k, label = label),
            fontface = "bold") +
  scale_color_manual(values = c("#6A9E1FFF", "#052F61FF")) +
  scale_x_continuous(breaks = seq(0, 500, 100),
                     expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0.01)) +
  facet_wrap(~ factor(scenario_label,
                      levels = c("None",
                                 "Strong stock",
                                 "Weak stock",
                                 "Both stocks")),
             nrow = 1) +
  labs(x = "",
       y = "N/K",
       color = "") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.spacing = unit(5, "mm"),
        strip.background = element_rect(fill = "transparent"),
        strip.text = element_text(color = "black", size = 10),
        axis.title.x = element_text(color = "black", size = 12, vjust = -2),
        axis.title.y = element_text(color = "black", size = 12, vjust = 2, face = "bold"),
        axis.text.y = element_text(color = "black", size = 10),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "bottom")

b_v_k_plot
```

```{r create effort plot}
effort_plot <-
  ggplot() +
  geom_line(data = out_effort_join %>% 
              mutate(effort = case_when(
                str_detect(effort, "_A") ~ "Fleet 1",
                str_detect(effort, "_B") ~ "Fleet 2"
              )),
            aes(x = time, y = effort_level, color = effort),
            linewidth = .8,
            alpha = .8) +
  facet_wrap(~ factor(scenario_label,
                      levels = c("None",
                                 "Strong stock",
                                 "Weak stock",
                                 "Both stocks")),
             nrow = 1) +
  scale_color_manual(values = c("black", "grey")) +
  scale_x_continuous(breaks = seq(0, 500, 100),
                     expand = c(0,0)) +
  scale_y_continuous(breaks = c(0, 10, 20, 30),
                     limits = c(0, 30),
                     expand = c(0, 0.5)) +
  labs(x = "",
       y = "Fishing Effort",
       color = "") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.spacing = unit(5, "mm"),
        strip.background = element_blank(),
        strip.text = element_blank(),
        axis.title.x = element_text(color = "black", size = 12),
        axis.title.y = element_text(color = "black", size = 12, vjust = 2, face = "bold"),
        axis.text.y = element_text(color = "black", size = 10),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "bottom")

effort_plot
```

```{r create price plot}
price_plot <- 
  ggplot() +
  geom_line(data = out_price_join,
            aes(x = time, y = price, color = stock_price),
            linewidth = .8,
            alpha = .8,
            show.legend = T) +
   facet_wrap(~ factor(scenario_label,
                       levels = c("None",
                                 "Strong stock",
                                 "Weak stock",
                                 "Both stocks")), 
              nrow = 1) +
  scale_color_manual(values = c("#6A9E1FFF", "#052F61FF", "red", "black")) +
  scale_x_continuous(breaks = seq(0, 500, 100),
                     expand = c(0,0)) +
  scale_y_continuous(breaks = seq(0, 10, by = 2),
                    expand = c(0,0.01)) +
  labs(x = "",
       y = "Price",
       color = "") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.spacing = unit(5, "mm"),
        strip.background = element_blank(),
        strip.text = element_blank(),
        axis.title.x = element_text(color = "black", size = 12),
        axis.title.y = element_text(color = "black", size = 12, vjust = 2, face = "bold"),
        axis.text.y = element_text(color = "black", size = 10),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "bottom")

price_plot
```


```{r create catch plot}
catch_plot <- 
  ggplot() +
  geom_line(data = out_catch_join,
            aes(x = time, y = catch_size, color = stock_catch),
            linewidth = .8,
            alpha = .8,
            show.legend = T) +
  facet_wrap(~ factor(scenario_label,
                      levels = c("None",
                                 "Strong stock",
                                 "Weak stock",
                                 "Both stocks")),
             nrow = 1) +
  scale_color_manual(values = c("#6A9E1FFF", "#052F61FF", "red", "black")) +
  scale_x_continuous(breaks = seq(0, 500, 100),
                     expand = c(0,0)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.25),
                     expand = c(0,0.01)) +
  labs(x = "",
       y = "Catch",
       color = "") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.spacing = unit(5, "mm"),
        strip.background = element_blank(),
        strip.text = element_blank(),
        axis.title.x = element_text(color = "black", size = 12),
        axis.title.y = element_text(color = "black", size = 12, vjust = 2, face = "bold"),
        axis.text.y = element_text(color = "black", size = 10),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "bottom")

catch_plot
```

```{r create cpue plot}
cpue_plot <- 
  ggplot() +
  geom_line(data = out_cpue_join,
            aes(x = time, y = cpue_level, color = stock_cpue),
            linewidth = .8,
            alpha = .8,
            show.legend = T) +
  facet_wrap(~ factor(scenario_label,
                      levels = c("None",
                                 "Strong stock",
                                 "Weak stock",
                                 "Both stocks")),
             nrow = 1) +
  scale_color_manual(values = c("#6A9E1FFF", "#052F61FF")) +
  scale_x_continuous(breaks = seq(0, 500, 100),
                     expand = c(0,0)) +
  scale_y_continuous(breaks = seq(0, 0.1, 0.02),
                     expand = c(0, 0.001)) +
  labs(x = "",
       y = "CPUE",
       color = "") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.spacing = unit(5, "mm"),
        strip.background = element_blank(),
        strip.text = element_blank(),
        axis.title.x = element_text(color = "black", size = 12),
        axis.title.y = element_text(color = "black", size = 12, vjust = 2, face = "bold"),
        axis.text.y = element_text(color = "black", size = 10),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "bottom")

cpue_plot
```



```{r create profit plot, fig.width=8, fig.height=6}
profit_plot <- 
  ggplot() +
  geom_line(data = out_profit_join,
            aes(x = time, y = profit_level),
            linewidth = .8,
            alpha = .8,
            color = "brown",
            show.legend = F) +
  # geom_hline(yintercept = 0,
  #            color = "gray30",
  #            linetype = "dashed",
  #            alpha = 0.5) +
  facet_wrap(~ factor(scenario_label,
                      levels = c("None",
                                 "Strong stock",
                                 "Weak stock",
                                 "Both stocks")),
             nrow = 1) +
  scale_x_continuous(breaks = seq(0, 500, 100),
                     expand = c(0,0)) +
  scale_y_continuous(expand = c(0, 0.01)) +
  labs(x = "Time",
       y = "Fishery profit",
       color = "") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.spacing = unit(5, "mm"),
        strip.background = element_blank(),
        strip.text = element_blank(),
        axis.title.x = element_text(color = "black", size = 12, face = "bold"),
        axis.title.y = element_text(color = "black", size = 12, vjust = 2, face = "bold"),
        axis.text = element_text(color = "black", size = 10),
        legend.position = "bottom")

profit_plot
```


# Plot 
```{r, fig.width=10, fig.height=15}
full_plot <- 
  b_v_k_plot +
  plot_spacer() +
  cpue_plot +
  plot_spacer() +
  effort_plot +
  plot_spacer() + 
  price_plot +
  plot_spacer() +
  profit_plot +
  plot_layout(ncol = 1,
              guides = "collect",
              heights = c(4, -0.6, 4, -0.6, 4, -0.6, 4, -0.6, 4)) &
  theme(legend.position = "bottom")

full_plot

 ggsave(file.path(outdir, "full_ts_plot_two_efforts.png"), plot =  full_plot,
       width = 8, height = 10, bg = "white", dpi = 300)
 
 # ggsave(file.path(outdir, "pub_ready", "figure_4.pdf"), plot =  full_plot,
 #       width = 8, height = 10, bg = "white", dpi = 600)
```

# create plot with isoclines mimicking Burgess (2015)

```{r}
out_stock_join_wide <- out_stock_join %>% 
  select(-b_v_k) %>% 
  pivot_wider(names_from = "stock",
              values_from = "stock_size") %>% 
  distinct() %>% 
  clean_names()

out_effort_join_wide <- out_effort_join %>% 
  mutate(effort_join = case_when(
    str_detect(effort, "1") ~ "effort_1",
    str_detect(effort, "2") ~ "effort_2",
    str_detect(effort, "3") ~ "effort_3",
    str_detect(effort, "4") ~ "effort_4"  
  )) %>% 
  group_by(scenario_label, time) %>% 
  mutate(effort_sum = sum(effort_level)) %>% 
  select(-c(effort, effort_level)) %>% 
  distinct() 

# join effort and stock datasets
out_stock_effort <- out_stock_join_wide %>% 
  left_join(out_effort_join_wide, by = c("time", "scenario_label"))
```

```{r, fig.width=8, fig.height=10}
ggplot() +
   geom_point(data = out_stock_effort,
              aes(x = strong_stock, y = weak_stock),
              alpha = 0.6) +
  geom_point(data = out_stock_effort,
            aes(x = effort_sum, y = weak_stock, color ),
            color = "blue",
            alpha = 0.6) +
  facet_wrap(~ factor(scenario_label,
                      levels = c("None",
                                 "Strong stock",
                                 "Weak stock",
                                 "Both stocks"))) +
  scale_x_continuous(expand = c(0,0),
                     limits = c(0, 30)) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0, 20)) +
  theme_bw()
```
















