---
title: "parametric-plots"
author: "Leonardo Feitosa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
# setting parameter values
k_s = 100
k_w = 50
q_s = 0.01
q_w = 0.01
r_s = 1
r_w = 0.5
p_w = 1
p_s = 1
c <- 0.005

# setting the sequence of values for state variables
E <- seq(0, 10, by = 0.5)
```


```{r}
# equations
N_s = - k_s * (E * q_s - r_s) / (r_s)

N_w = - k_w * (E * q_w - r_w) / (r_w)

profit_Nw = c - p_s * q_s * N_s / p_w * q_w

profit_Ns = c - p_w * q_w * N_w / p_s * q_s
```

```{r}
# Calculating profits for a given effort level, assuming it affects both populations
profit <- p_s * q_s * N_s + p_w * q_w * N_w - c

# Creating a data frame for plotting
data <- data.frame(E, N_s, N_w, profit_Nw, profit_Ns)

# Plotting
ggplot() +
  geom_line(data = data, aes(x = N_w, y = N_s),
            color = "black") +
  geom_line(data = data,
            aes(x = profit_Nw, y = profit_Ns),
            color = "blue") +
  labs(x = "N_w", y = "N_s", title = "Parametric plot of N_s vs N_w and Profits") +
  scale_color_manual(values = c("Population Sizes" = "blue", "Profits" = "red")) +
  theme_minimal()
```

```{r}
# Create a sequence of effort levels
e <- seq(0, 100, by = 1)

# Solve for Ns and Nw at each effort level
N_s = - k_s * (e * q_s - r_s) / (r_s)
N_w = - k_w * (e * q_w - r_w) / (r_w)
N_w_profit <- k_w * (e * k_s * q_s - e * k_s * q_w - k_s * r_s + N_s * r_s + k_s * r_w) / (k_s * r_w)
N_s_e <- c - N_s * p_s * q_s / (p_w * q_w)
N_w_e <- c - N_w * p_w * q_w / (p_s * q_s)

# Create a data frame for plotting
data <- data.frame(e, N_s, N_w, N_w_profit, N_s_e, N_w_e) 

# Create the plot
ggplot() +
  geom_line(data = data,
            aes(x = N_s, y = N_w_e, color = "N_w_e")) +
  geom_line(data = data,
            aes(x = N_s, y = N_w_profit, color = "N_w_profit")) +
  geom_point(data = data %>% filter(N_w == 0), 
             aes(x = N_s, y = N_w), 
             color = "black", 
             fill = "white",
             pch = 21,
             size = 5) +
  scale_x_continuous(limits = c(0, 100),
                     expand = c(0,0)) +
  scale_y_continuous(limits = c(0, 50),
                     expand = c(0,0)) +
  labs(x = "Ns", y = "Nw", title = "Parametric Plot of Ns vs. Nw", color = "") +
  theme_bw() +
  theme(panel.grid = element_blank()) +
  scale_color_manual(values = c("N_w_e" = "black", "N_w_profit" = "blue"), 
                     labels = c("N_w_e" = "Effort", "N_w_profit" = "Profits"))
```

```{r}
A_w = 1
A_s = 1
beta_w = 0.56
f_w = 0.22
beta_s = 0.56
f_s = 0.22

# Create a sequence of effort levels
e <- seq(0, 100, by = 1)

# Solve for Ns and Nw at each effort level
N_s = - k_s * (e * q_s - r_s) / (r_s)
N_w = - k_w * (e * q_w - r_w) / (r_w)
N_w_profit <- k_w * (e * k_s * q_s - e * k_s * q_w - k_s * r_s + N_s * r_s + k_s * r_w) / (k_s * r_w)
N_s_e <- c - N_s * (A_s * (q_s * N_s^beta_s * e)^-f_s) * q_s / ((A_w * (q_w * N_w^beta_w * e)^-f_w) * q_w)
N_w_e_flex <- c - N_w * (A_w * (q_w * N_w^beta_w * e)^-f_w) * q_w / ((A_s * (q_s * N_s^beta_s * e)^-f_s) * q_s)
N_w_profit2 <- - N_s * (A_w * (q_w * N_w^beta_w * e)^-f_w) * q_s / ((A_w * (q_w * N_w^beta_w * e)^-f_w) * q_w)
# Create a data frame for plotting
data_flex <- data.frame(e, N_s, N_w, N_w_profit, N_s_e, N_w_e_flex, N_w_profit2) 

# Create the plot
ggplot() +
  geom_line(data = data_flex,
            aes(x = N_s, y = N_w_e_flex, color = "N_w_e_flex")) +
    geom_line(data = data_flex,
            aes(x = N_s, y = N_w_profit, color = "N_w_profit2")) 
  geom_line(data = data_flex,
            aes(x = N_s, y = N_w_profit, color = "N_w_profit")) 
  geom_point(data = data_flex %>% filter(N_w == 0), 
             aes(x = N_s, y = N_w), 
             color = "black", 
             fill = "white",
             pch = 21,
             size = 5) +
  # scale_x_continuous(limits = c(0, 100),
  #                    expand = c(0,0)) +
  # scale_y_continuous(limits = c(0, 50),
  #                    expand = c(0,0)) +
  labs(x = "Ns", y = "Nw", title = "Parametric Plot of Ns vs. Nw", color = "") +
  theme_bw() +
  theme(panel.grid = element_blank()) +
  scale_color_manual(values = c("N_w_e" = "black", "N_w_profit" = "blue"), 
                     labels = c("N_w_e" = "Costs", "N_w_profit" = "Profits"))
```