---
title: "lecture_sim"
author: "Leonardo Feitosa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
library(tidyverse)
library(patchwork)
```



```{r}
# define general parameters
c <- 0.05       # cost per unit of fishing effort
alpha <- 1      # response rate of effort to profits
A_byc <- 1      # response rate of price to changes in catch
A_tgt <- 1      # response rate of price to changes in catch
q_tgt <- 0.02   # catchability of each stock
q_byc <- 0.02   # catchability of each stock
k_tgt <- 4      # carrying capacity 
k_byc <- 2      # carrying capacity 
beta_tgt1 <- 1  # hyperstability coefficient
beta_byc1 <- 1  # hyperstability coefficient
f_tgt1 <- 0     # price flexibility coefficient 
f_byc1 <- 0     # price flexibility coefficient

############ YOU ONLY CHANGE THESE ##################
r_tgt <- 1       # intrinsic population growth rate
r_byc <- 0.5      # intrinsic population growth rate

# time steps
times <- seq(1, 200, by = 1)
delta_t <- 1
n = 200
```

```{r}
# create place holder vectors
exp.target <- rep(NaN, n)
exp.bycatch <- rep(NaN, n)
exp.effort <- rep(NaN, n)

# setting initial values for each variable
exp.target[1] <- k_tgt
exp.bycatch[1] <- k_byc
exp.effort[1] <- 0.5
```


```{r}
# run simulation
for(i in 2:length(exp.target)){ 
    dN_target <- (r_tgt * exp.target[i-1] * (1 - (exp.target[i-1]/k_tgt)) - (q_tgt * exp.target[i-1]^beta_tgt1 * exp.effort[i-1])) * delta_t
    dN_bycatch <- (r_byc * exp.bycatch[i-1] * (1 - (exp.bycatch[i-1]/k_byc)) - (q_byc * exp.bycatch[i-1]^beta_byc1 * exp.effort[i-1])) * delta_t
    d_effort <- (alpha * exp.effort[i-1] * 
       (A_tgt * (q_tgt * exp.target[i-1]^beta_tgt1 * exp.effort[i-1])^-f_tgt1 * q_tgt * exp.target[i-1]^beta_tgt1 +
                         A_byc * (q_byc * exp.bycatch[i-1]^beta_byc1 * exp.effort[i-1])^-f_byc1 * q_byc * exp.bycatch[i-1]^beta_byc1 - (c))) * delta_t
    
    exp.target[i] <- exp.target[i-1] + dN_target
    exp.bycatch[i] <- exp.bycatch[i-1] + dN_bycatch
    exp.effort[i] <- exp.effort[i-1] + d_effort
    
}

# store results in a tidy data frame
sim_df <- data.frame(target = exp.target,   # divides population size per carrying capacity
                    bycatch = exp.bycatch, # divides population size per carrying capacity
                    tgt_div_k = exp.target/k_tgt,   # divides population size per carrying capacity
                    byc_div_k = exp.bycatch/k_byc, # divides population size per carrying capacity
                    effort = exp.effort,
                    time = times,
                    r_tgt = r_tgt,
                    r_byc = r_byc,
                    k_tgt = k_tgt,
                    k_byc = k_byc,
                    q_tgt = q_tgt,
                    q_byc = q_byc) %>% 
  pivot_longer(cols = target:bycatch, # tidy absolute abundances for kobe plot
               names_to = "model_vars_abs",
               values_to = "abs_values") %>% 
  pivot_longer(cols = tgt_div_k:byc_div_k, # tidy relative abundances for ts plot
               names_to = "model_vars_rel",
               values_to = "b_div_k") 
```

```{r}
# plots population/carrying capacity ratio

pop <- 
  ggplot(data = sim_df %>% 
           mutate(stocks = ifelse(model_vars_rel == "tgt_div_k", "Target", "Bycatch"))) +
  geom_line(aes(x = time, y = b_div_k, color = stocks),
            linewidth = 1,
            alpha = 0.7) +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  annotate(geom = "text", label = "Not overfished", x = 180, y = 0.55, size = 4) +
  annotate(geom = "text", label = "Overfished", x = 180, y = 0.45, size = 4) +
  scale_y_continuous(breaks = seq(0, 1, 0.25),
                     limits = c(0, 1)) +
  labs(x = "Time",
       y = "N/K",
       color = "Species") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank())

pop
```

```{r}
# Plots change in fishing effort over time
effort <-
  ggplot(data = sim_df) +
  geom_line(aes(x = time, y = effort)) +
  labs(x = "Time",
       y = "Fishing Effort",
       color = "Species") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank())

```


```{r, fig.height=8, fig.width=6}
pop / effort
```



# Let's plot your stocks on a Kobe plot

```{r}
# parameters to calculate biomass
weight_tgt = 1
weight_byc = 1


sim_df_kobe <- sim_df %>% 
  filter(time == 200) %>% 
  pivot_wider(names_from = "model_vars_abs",
              values_from = "abs_values")  %>% 
  mutate(b_tgt_eq = target * weight_tgt,
         b_byc_eq = bycatch * weight_byc,
         f_tgt_eq = target / b_tgt_eq,
         f_byc_eq = bycatch / b_byc_eq,
         msy_tgt = 0.5 * b_tgt_eq * f_tgt_eq,
         msy_byc = 0.5 * b_byc_eq * f_byc_eq,
         b_msy_tgt = k_tgt * f_tgt_eq,
         b_msy_byc = k_byc * f_byc_eq,
         bs_div_bmsy = b_tgt_eq/ b_msy_tgt,
         bw_div_bmsy = b_byc_eq/ b_msy_byc,
         f_msy_tgt = r_tgt / (2 * q_tgt),
         f_msy_byc = r_byc / (2 * q_byc),
         fs_div_fmsy = f_tgt_eq / f_msy_tgt,
         fw_div_fmsy = f_byc_eq / f_msy_byc) %>% 
  select(model_vars_rel, bs_div_bmsy, bw_div_bmsy, fs_div_fmsy, fw_div_fmsy) %>% 
  pivot_longer(cols = c(bs_div_bmsy, bw_div_bmsy, fs_div_fmsy, fw_div_fmsy),
               names_to = c("stock", "ref_point"),
               names_sep = "_div_",
               values_to = "value")
  
sim_df_kobe_st <- sim_df_kobe %>% 
  select(-model_vars_rel) %>% 
  filter(str_detect(stock, "s")) %>% 
  group_by(ref_point) %>% 
  slice_max(n = 2, order_by = value) %>% 
  distinct() %>% 
  ungroup() %>% 
  pivot_wider(names_from = "stock", values_from = "value") %>% 
  mutate(stock = "Strong") %>% 
  select(-ref_point) %>% 
  fill("fs", .direction = "up") %>% 
  drop_na(bs)

sim_df_kobe_weak <- sim_df_kobe %>% 
  select(-model_vars_rel) %>% 
  filter(str_detect(stock, "w")) %>% 
  group_by(ref_point) %>% 
  slice_max(n = 2, order_by = value) %>% 
  distinct() %>% 
  ungroup() %>% 
  pivot_wider(names_from = "stock", values_from = "value") %>% 
  mutate(stock = "Weak") %>% 
  select(-ref_point) %>% 
  fill("fw", .direction = "up") %>% 
  drop_na(bw)
  
    


```

```{r}
ggplot() +
  geom_point(data = sim_df_kobe_st, 
             aes(x = bs, y = fs, color = stock), 
             size = 4) +
  geom_point(data = sim_df_kobe_weak,
             aes(x = bw, y = fw, color = stock), 
             size = 4) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "black", linewidth = 1) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "black", linewidth = 1) +
  scale_x_continuous(breaks = seq(0, 2, 0.5),
                     limits = c(0, 2)) +
  scale_y_continuous(breaks = seq(0, 2, 0.5),
                     limits = c(0, 2)) +
  labs(x = "B/Bmsy", y = "F/Fmsy", color = "Stocks", shape = "Stocks", title = "Kobe plot") +
  theme_bw() +
  theme(panel.grid = element_blank())
```


```{r}
ggplot(data = sim_df_kobe) +
  geom_point(aes(x = biom_value, y = f_value, color = stocks, shape = stocks),
             size = 2) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "black", linewidth = 1) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "black", linewidth = 1) +
  scale_x_continuous(breaks = c(0, 2, 0.5),
                     limits = c(0, 2)) +
  scale_y_continuous(breaks = c(0, 2, 0.5),
                     limits = c(0, 2)) +
  labs(x = "B/Bmsy",
       y = "F/Fmsy",
       color = "Stocks",
       shape = "Stocks",
       title = "Kobe plot") +
  theme_bw()
```























